=== abinashacharya0206/RestAssuredUdemyCourse/restAssured/resources/JsonSchema.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "id",
      "name",
      "age",
      "department",
      "salary"
    ],
    "properties": {
      "id": {
        "type": "number"
      },
      "name": {
        "type": "string",
        "minLength": 1
      },
      "age": {
        "type": "number"
      },
      "department": {
        "type": "string",
        "minLength": 1
      },
      "salary": {
        "type": "number"
      }
    }
  }
}

=== abinashacharya0206/RestAssuredUdemyCourse/restAssured/resources/stubtwo.json
[
    {
        "id": 1,
        "name": "John Doe",
        "age": 30,
        "department": "HR",
        "salary": 50000.00
    },
    {
        "id": 2,
        "name": "Alice Smith",
        "age": 35,
        "department": "Engineering",
        "salary": 60000.00
    },
    {
        "id": 3,
        "name": "Bob Johnson",
        "age": 28,
        "department": "Marketing",
        "salary": 55000.00
    },
    {
        "id": 4,
        "name": "Emily Brown",
        "age": 32,
        "department": "Sales",
        "salary": 52000.00
    },
    {
        "id": 5,
        "name": "Michael Lee",
        "age": 40,
        "department": "Finance",
        "salary": 70000.00
    },
    {
        "id": 6,
        "name": "Pat Cummins",
        "age": 31,
        "department": "Cricket",
        "salary": 20000.00
    },
    {
        "id": 7,
        "name": "Sunil Narine",
        "age": 36,
        "department": "Cricket",
        "salary": 21000.00
    },
    {
        "id": 8,
        "name": "Sunil Mhatre",
        "age": 45,
        "department": "Football",
        "salary": 55000.00
    },
    {
        "id": 9,
        "name": "Sunil Kharge",
        "age": 48,
        "department": "Baseball",
        "salary": 20000.00
    },
    {
        "id": 10,
        "name": "Marie Curie",
        "age": 30,
        "department": "R&D",
        "salary": 35000.00
    },
    {
        "id": 11,
        "name": "Manik Chand",
        "age": 30,
        "department": "Chemist",
        "salary": 40000.00
    },
    {
        "id": 12,
        "name": "Danavira",
        "age": 30,
        "department": "Druggist",
        "salary": 30000.00
    },
    {
        "id": 13,
        "name": "Manik Chand",
        "age": 30,
        "department": "Chemist",
        "salary": 40000.00
    },
    {
        "id": 14,
        "name": "Marie Marie",
        "age": 30,
        "department": "R&D",
        "salary": 35000.00
    },
    {
        "id": 15,
        "name": "Manik Manik",
        "age": 30,
        "department": "Chemist",
        "salary": 40000.00
    }
]
